In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats

tips = sns.load_dataset("tips")
titanic = sns.load_dataset('titanic')
titanic.dropna(inplace=True)
penguins = sns.load_dataset("penguins")
iris = sns.load_dataset('iris')
dia = sns.load_dataset("diamonds")

In [2]:
from sklearn.naive_bayes import GaussianNB

In [3]:
model = GaussianNB()

In [6]:
model.fit(X=iris.iloc[:,:-1],y=iris['species'])

GaussianNB()

In [9]:
iris['species'].value_counts(normalize=True)

setosa        0.333333
versicolor    0.333333
virginica     0.333333
Name: species, dtype: float64

In [10]:
model.class_prior_

array([0.33333333, 0.33333333, 0.33333333])

In [12]:
model.theta_ #베이시안 계수

array([[5.006, 3.428, 1.462, 0.246],
       [5.936, 2.77 , 4.26 , 1.326],
       [6.588, 2.974, 5.552, 2.026]])

In [16]:
pred_proba = model.predict_proba(iris.iloc[:,:4])

In [17]:
pred = model.predict(iris.iloc[:,:4])

In [19]:
iris['predict']=pred

In [21]:
iris

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

       predict  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 6 columns]

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats

tips = sns.load_dataset("tips")
titanic = sns.load_dataset('titanic')
titanic.dropna(inplace=True)
penguins = sns.load_dataset("penguins")
iris = sns.load_dataset('iris')
dia = sns.load_dataset("diamonds")

In [3]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB

In [4]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
iris['species'].value_counts(normalize=True) # 사전확률

setosa        0.333333
versicolor    0.333333
virginica     0.333333
Name: species, dtype: float64

In [8]:
model = GaussianNB()

In [9]:
model.fit(iris.iloc[:,:-1],iris.iloc[:,-1])

GaussianNB()

In [10]:
model.class_count_

array([50., 50., 50.])

In [11]:
model.class_prior_ #종속변수 사전 확률 
#iris['species'].value_counts(normalize=True) 

array([0.33333333, 0.33333333, 0.33333333])

In [13]:
model.theta_ #모델 계수

array([[5.006, 3.428, 1.462, 0.246],
       [5.936, 2.77 , 4.26 , 1.326],
       [6.588, 2.974, 5.552, 2.026]])

In [16]:
pred = model.predict(iris.iloc[:,:4])

In [17]:
pred

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'virginica', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica',

In [19]:
iris.iloc[:,:]

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]